site_name: Scripts IEEE UFABC
pages:
  - "Início": "index.md"
  - Scripts:
    - "Movimentações": "Scripts/movimentacoes.md"
    - "Recibos": "Scripts/recibos.md" 
    - "Agenda": "Scripts/agenda.md" 
theme: readthedocs
extra_javascript:
  - extra.js
extra_css:
  - extra.css
repo_url: https://github.com/AdsonBatista/Scripts-automatizacao
