site_name: Scripts IEEE UFABC
pages:
  - "Início": "index.md"
theme: readthedocs
extra_javascript:
  - extra.js
extra_css:
  - extra.css
repo_url: https://github.com/AdsonBatista/Scripts-automatizacao
