site_name: Scripts IEEE UFABC
pages:
  - "Início": "index.md"
  - "Movimentações": "movimentacoes.md"
  - "Recibos": "recibos.md" 
  - "Agenda": "agenda.md" 
theme: readthedocs
extra_javascript:
  - extra.js
extra_css:
  - extra.css
repo_url: https://github.com/AdsonBatista/Scripts-automatizacao
